DOMAIN = 'localhost:8000'
ADMIN_UN = 'jmoxon'
ADMIN_UE = ''
ADMIN_PW = ''
DB_ENGINE = 'sqlite3' # mysql                                                            
DB_USER = ''
DB_PASSWORD = ''
DB_HOST = ''
DB_PORT =  3306
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT =  587
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_TLS = True
